=== Jaimelah/SS_Practica1/target/classes/practica1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.unican.es/ss/practica1Banco"
	xmlns="http://www.unican.es/ss/practica1Banco"
	elementFormDefault="qualified">
<!-- Completado -->
	<xs:complexType name="Valor">
		<xs:attribute name="nombreEntidad" type="xs:string"
			use="required" />
		<xs:attribute name="numeroAcciones" type="xs:integer"
			use="required" />
		<xs:attribute name="ultimoValorCotizado" type="xs:double"
			use="required" />
	</xs:complexType>

	<xs:simpleType name="dni">
		<xs:restriction base="xs:string">
			<xs:length value="10" />
			<xs:pattern
				value="[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][A-Z]" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="tipoCuentaAhorro">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Oro" />
			<xs:enumeration value="Joven" />
			<xs:enumeration value="Normal" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="numeroCuenta">
		<xs:restriction base="xs:integer">
			<xs:pattern value="\d{20,20}" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="cvc">
		<xs:restriction base="xs:integer">
			<xs:pattern value="\d{3,3}" />
		</xs:restriction>
	</xs:simpleType>

<!-- Completado -->
	<xs:complexType name="ProductoBancario" abstract="true">
		<xs:attribute name="idProductoBancario" type="xs:ID" use="required"/>
	</xs:complexType>

<!-- Completado -->
	<xs:complexType name="CuentaAhorro">
		<xs:complexContent>
			<xs:extension base="ProductoBancario">
				<xs:attribute name="numeroCuenta" type="numeroCuenta"
					use="required" />
				<xs:attribute name="fechaApertura" type="xs:date"
					use="required" />
				<xs:attribute name="saldo" type="xs:double"
					use="required" />
				<xs:attribute name="tipo" type="tipoCuentaAhorro"
					use="required" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
<!-- Completado -->
	<xs:complexType name="CuentaValores">
		<xs:complexContent>
			<xs:extension base="ProductoBancario">
				<xs:sequence>
					<xs:element name="valorCuenta" type="Valor"
						maxOccurs="unbounded" minOccurs="1" />
				</xs:sequence>
				<xs:attribute name="accionesEnBolsa" type="xs:integer"
					use="required" />
				<xs:attribute name="fechaApertura" type="xs:date"
					use="required" />
				<xs:attribute name="numeroCuenta" type="numeroCuenta"
					use="required" />

			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
<!-- Completado -->
	<xs:complexType name="DepositoPlazoFijo">
		<xs:complexContent>
			<xs:extension base="ProductoBancario">
				<xs:attribute name="importeDepositado" type="xs:double"
					use="required" />
				<xs:attribute name="tipoInteres" type="xs:string"
					use="required" />
				<xs:attribute name="fechaVencimiento" type="xs:date"
					use="required" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
<!-- Completado -->
	<xs:complexType name="Tarjeta">
		<xs:complexContent>
			<xs:extension base="ProductoBancario">
				<xs:attribute name="numeroTarjeta" type="xs:integer"
					use="required" />
				<xs:attribute name="fechaCaducidad" type="xs:date"
					use="required" />
				<xs:attribute name="CVC" type="cvc" use="required" />
				<xs:attribute name="numeroCuenta" type="numeroCuenta"
					use="required" />
				<xs:attribute name="refCuentaAhorro" type="xs:IDREF" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
<!-- Completado -->
	<xs:complexType name="Cliente">
		<xs:sequence>
			<xs:element name="producto" type="ProductoBancario"
				maxOccurs="unbounded" minOccurs="1" />
		</xs:sequence>
		<xs:attribute name="nombre" type="xs:string"
			use="required" />
		<xs:attribute name="apellido1" type="xs:string"
			use="required" />
		<xs:attribute name="apellido2" type="xs:string" />
		<xs:attribute name="DNI" type="dni" use="required" />
	</xs:complexType>

	<xs:element name="Banco">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="cliente" type="Cliente"
					maxOccurs="unbounded" minOccurs="0" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== Jaimelah/SS_Practica1/target/classes/Practica1_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:Banco xmlns:p="http://www.unican.es/ss/practica1Banco"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.unican.es/ss/practica1Banco practica1.xsd ">
	<p:cliente idUsuario="user1" apellido1="q" DNI="111111111A" nombre="n"
		apellido2="q">
		<p:producto xsi:type="p:CuentaAhorro"
			idProductoBancario="A" fechaApertura="2020-01-02"
			numeroCuenta="12345678901234567891" saldo="1.0" tipo="Oro" />
		<p:producto xsi:type="p:CuentaValores"
			idProductoBancario="B" 
			fechaApertura="2020-01-02" numeroCuenta="10101010101010101010">
			<p:valorCuenta numeroAcciones="1" nombreEntidad="E"
				ultimoValorCotizado="10" />
		</p:producto>
		<p:producto xsi:type="p:DepositoPlazoFijo"
			idProductoBancario="C" fechaVencimiento="2020-01-10"
			importeDepositado="100" tipoInteres="interes1" />
		<p:producto xsi:type="p:Tarjeta" CVC="111"
			idProductoBancario="D" fechaCaducidad="2020-10-10"
			numeroCuenta="12345678901234567891" numeroTarjeta="1231231231231313"
			refCuentaAhorro="A" />
	</p:cliente>
	<p:cliente idUsuario="user2" apellido1="q" DNI="111111111A" nombre="n"
		apellido2="q">
		<p:producto xsi:type="p:CuentaAhorro"
			idProductoBancario="Z" fechaApertura="2020-01-02"
			numeroCuenta="12345678901234567891" saldo="1" tipo="Oro" />
		<p:producto xsi:type="p:CuentaValores"
			idProductoBancario="qw" 
			fechaApertura="2020-01-02" numeroCuenta="10101010101010101010">
			<p:valorCuenta numeroAcciones="2" nombreEntidad="E"
				ultimoValorCotizado="10" />
		</p:producto>
		<p:producto xsi:type="p:DepositoPlazoFijo"
			idProductoBancario="wqe" fechaVencimiento="2020-01-10"
			importeDepositado="100" tipoInteres="interes1" />
		<p:producto xsi:type="p:Tarjeta" CVC="111"
			idProductoBancario="Dqweq" fechaCaducidad="2020-10-10"
			numeroCuenta="12345678901234567891" numeroTarjeta="1231231231313121"
			refCuentaAhorro="A" />
	</p:cliente>
</p:Banco>
